# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Koa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Koa
  pod 'lottie-ios'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  target 'KoaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
